### ISSUE TITLE
About BatchClipping

### ISSUE THREAD

**Issue by lc827323702** [zihangxiang/A-Theory-to-Instruct-Differentially-Private-Learning-via-Clipping-Bias-Reduction#1]
May I ask where the BatchClipping algorithm is described in the code, but I don't see any BatchClipping algorithm.

**Comment by zihangxiang** [comment]
Hi, It is not included in the code base yet. We may consider adding it later.

**Comment by lc827323702** [comment]
Fine, I'd appreciate it if the code for the BatchClipping algorithm could be open accessed.
